# Generated by Django 2.2.5 on 2019-09-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=300)),
                ('cash', models.FloatField()),
                ('trans_type', models.BooleanField()),
            ],
        ),
    ]
