# Generated by Django 2.2.5 on 2019-09-06 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trym', '0003_auto_20190906_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cash',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date(2019, 9, 6)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='Some description.', max_length=300),
        ),
    ]
