# Generated by Django 2.2.5 on 2019-10-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trym', '0005_auto_20190909_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cash',
            new_name='value',
        ),
    ]
