# Generated by Django 2.2.5 on 2019-09-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_first_day_of_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_day_of_month',
        ),
    ]
