# Generated by Django 2.2.5 on 2019-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyb', '0002_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='trans_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('P', 'Profit'), ('T', 'Tax'), ('B', 'Buy')], default='B', max_length=1),
        ),
    ]
